### ISSUE TITLE
3D Saliency

### ISSUE THREAD

**Issue by jdcuevas-lbl** [marcoancona/DeepExplain#16]
If I wanted to generate a 3D saliency map of a 64x64x64 input with 8 channels, how could I go about doing it?

**Comment by marcoancona** [comment]
Not sure I understand the setting.
Your model input is 64x64x64x8, correct?
DeepExplain generates an attribution value for *each* input feature so your attribution map would have the same size of the input. Then it is up to you how to visualize such multidimensional vector.


Il giorno 23 lug 2018, alle ore 20:43, jdcuevas-lbl <notifications@github.com<mailto:notifications@github.com>> ha scritto:


If I wanted to generate a 3D saliency map of a 64x64x64 input with 8 channels, how could I go about doing it?

**Comment by jdcuevas-lbl** [comment]
I figured that out. I do have another question however. If my input is 512x512 with 8 channels, will an attribution map be generated for each of the channels of information?
