### ISSUE TITLE
Using contributions for k-NN search

### ISSUE THREAD

**Issue by EoinKenny** [marcoancona/DeepExplain#17]
Hi, please bear with me as this is an usual issue.

I am attempting to use LRP and Integrated Gradients in a different way. I would like to use this library to get the contributions of various features to the prediction of a standard (one hidden layer) Keras NN.

So I have the data modelled, my X_train, y_train, X_test, y_test all set up.

I run the following code (from your example)

```
with DeepExplain(session=K.get_session()) as de:  # <-- init DeepExplain context
    input_tensor = model.layers[0].input
    fModel = Model(inputs=input_tensor, outputs = model.layers[-2].output)
    target_tensor = fModel(input_tensor)
    
    xs = X_train
    ys = np.array([y_train]).T
    
X_train_intgrad = de.explain('intgrad', target_tensor * ys, input_tensor, xs)
X_train_lrp = de.explain('elrp', target_tensor * ys, input_tensor, xs)
    
    
with DeepExplain(session=K.get_session()) as de:  # <-- init DeepExplain context
    input_tensor = model.layers[0].input
    fModel = Model(inputs=input_tensor, outputs = model.layers[-2].output)
    target_tensor = fModel(input_tensor)
    
    xs = X_test
    ys = np.array([y_test]).T
    
X_test_intgrad = de.explain('intgrad', target_tensor * ys, input_tensor, xs)
X_test_lrp = de.explain('elrp', target_tensor * ys, input_tensor, xs)
```
And it works okay (although I noticed that DeepLIFT appears to get an error, but that's a separate issue).

However, when I use these contributions to do a k-NN search for classification (instead of the feature values which would be normal) I get 100% accuracy. 

This is obviously a mistake, but I have been trying for a while to understand why and I cannot get to the bottom of it. Could you help me understand my mistake? 

Thanks so much for these implementations! By the way, the output neuron is a sigmoid unit if that's relevant.

**Comment by marcoancona** [comment]
If I understand correctly, you are using k-NN on the attribution maps, correct? I can't say why that gets 100% accuracy, especially without seeing the full code. What is the accuracy of the "normal" Keras model?

**Comment by EoinKenny** [comment]
Yes exactly, I am running the k-NN on the attribution maps. And for some reason it's getting 100% accuracy, which is very strange considering that the Keras NN gets 82.25% accuracy and the k-NN gets 78.94% normally.

The idea is that the attribution map would be more precise for a k-NN search.

Actually, I think I may have discovered the issue, is `ys` supposed to be the predictions of the NN or the labeled data in raw form?

Because I used the actual labeled data, which would certainly explain all this.

Actually the `ys` confused me because usually these libraries don't require the labels. Is there a reason you ask for it instead of just computing it?

**Comment by marcoancona** [comment]
Hey, yes using the actual labels (which is correct for DeepExplain) might explain the 100% accuracy of course. `ys` is only used to "select" a neuron in the output tensor. 
Assuming `ys` is one-hot encoded, multiplying the output with it would only pick the neuron corresponding to the correct class according to the ground-truth. This is to see what promoted/discouraged that class. You can also use the prediction of the network instead (making sure it is binary!) and this would show you what promoted/discouraged the neuron corresponding to the class chosen by the model. I think both might be useful.

**Comment by EoinKenny** [comment]
Thanks for the quick reply! 
So if I understand correctly I can either have 

```
xs = X_train
X_train_int_grad = de.explain('intgrad', target_tensor, input_tensor, xs)

```
or

```
xs = X_train
ys = model.predict(X_train)
X_train_int_grad = de.explain('intgrad', target_tensor * ys, input_tensor, xs)

```

There is only one output here, a single sigmoid unit. There is no one hot encoding...
So if I understand correctly I should use the second block of code in this post to see what contributed to that prediction?

**Comment by marcoancona** [comment]
In this case you should use the first version always. You have one output neuron only, therefore you always want to learn what is activating that neuron.
Different would be a multi-class classification task (ie. MNIST) where you might want to generate explanations for different classes, and therefore you would need to "select" which class to target (the correct class or the one predicted by the network).

**Comment by EoinKenny** [comment]
I understand, thank you @marcoancona!

**Comment by marcoancona** [comment]
You're welcome
