### ISSUE TITLE
'Garter Snake' attribution comparison example codes needed

### ISSUE THREAD

**Issue by yulongwang12** [marcoancona/DeepExplain#3]
Would you please include the example codes which can generate the 'Garter Snake' attribution comparison picture in `docs/comparison.png`? Actually I'm currently working on reproducing the results on PyTorch. The MNIST examples are comparable, but for snake picture, the attribution heatmaps are not salient. I want to know if any configurations have been made (like the initial relevance value `r_i` scaled ?) when performing on naturalistic images with imagenet-pretrained models. Thank you very much!

**Comment by marcoancona** [comment]
We have used Inception V3 and filtered the 99th percentile as suggested in https://arxiv.org/abs/1706.03825
Also make sure the colormap range is symmetric, in positive and negative values.
I will upload the code for it soon.

Il giorno 11 dic 2017, alle ore 18:42, Yulong Wang <notifications@github.com<mailto:notifications@github.com>> ha scritto:


Would you please include the example codes which can generate the 'Garter Snake' attribution comparison picture in docs/comparison.png? Actually I'm currently working on reproducing the results on PyTorch. The MNIST examples are comparable, but for snake picture, the attribution heatmaps are not salient. I want to know if any configurations have been made (like the initial relevance value r_i scaled ?) when performing on naturalistic images with imagenet-pretrained models. Thank you very much!

**Comment by marcoancona** [comment]
Closed in 2ed086953c07a0a1652cf0b0d6b9e1359fd03426
