### ISSUE TITLE
 If I run de.explain multiple times, it becomes slower and slower. 

### ISSUE THREAD

**Issue by linchundan88** [marcoancona/DeepExplain#34]
Thank for your work.

If I run de.explain multiple times, it becomes slower and slower. 

This problem has not been solved in v0.2.

**Comment by linchundan88** [comment]
I developed a RPC service to generate saliency maps using your great library. 
I load my models and create DeepExplain session before hand,  for every request from RPC client, RPC service invode de.explain. So I found it becomes slower and slower.

**Comment by marcoancona** [comment]
So, if I understood correctly, you call multiple times `explain()` with a different `xs` but the same Tensors T and X?

**Comment by linchundan88** [comment]
with DeepExplain(session=K.get_session()) as de:  # <-- init DeepExplain context
            input_tensor = model.layers[0].input

            fModel = Model(inputs=input_tensor, outputs=model.layers[-1].output)
            target_tensor = fModel(input_tensor)

            xs = img_preprocess
            ys = keras.utils.to_categorical([pred], NUM_CLASSES)

            for i in range(TEST_NUM):
                time1 = time.time()  #2 second faster than before   DeepExplain(session=K.get_session()) as de:
                attributions = de.explain('deeplift', target_tensor * ys, input_tensor, xs, batch_size=1)
                # attributions = de.explain('deeplift', target_tensor, input_tensor, xs, ys=ys)
                # attributions = de.explain('elrp', target_tensor * ys, input_tensor, xs, batch_size=1)
                # attributions = de.explain('shapley_sampling', target_tensor, input_tensor, xs, ys=ys, samples=100)
                time2 = time.time()
                print(time2-time1)

**Comment by linchundan88** [comment]
OR:

for i in range(TEST_NUM):
    
    time1 = time.time()  # 2 second faster than before   DeepExplain(session=K.get_session()) as de:
    with DeepExplain(session=K.get_session()) as de:  # <-- init DeepExplain context
    
        # Need to reconstruct the graph in DeepExplain context, using the same weights.
        # With Keras this is very easy:
        # 1. Get the input tensor to the original model
        input_tensor = model.layers[0].input
        
        fModel = Model(inputs=input_tensor, outputs=model.layers[-1].output)
        target_tensor = fModel(input_tensor)
        
        xs = img_preprocess
        ys = keras.utils.to_categorical([pred], NUM_CLASSES)
        
        # attributions = de.explain('grad*input', target_tensor * ys, input_tensor, xs)
        # attributions = de.explain('saliency', target_tensor * ys, input_tensor, xs)
        # attributions = de.5('intgrad', target_tensor * ys, input_tensor, xs)
        # GPU 4 seconds, CPU 6 Seconds
        
        
        
        attributions = de.explain('deeplift', target_tensor * ys, input_tensor, xs, batch_size=1)
        # attributions = de.explain('deeplift', target_tensor, input_tensor, xs, ys=ys)
        # attributions = de.explain('elrp', target_tensor * ys, input_tensor, xs, batch_size=1)
        # attributions = de.explain('shapley_sampling', target_tensor, input_tensor, xs, ys=ys, samples=100)
 
    time2 = time.time()
    print(time2 - time1)

**Comment by linchundan88** [comment]
If I execute k.clear_session() and load model every time,  execution time is stable.
