### ISSUE TITLE
Error if dimensions other than first are None for the input vector

### ISSUE THREAD

**Issue by linchundan88** [marcoancona/DeepExplain#36]
if some dimensions of input are not specified,  for example `(None, None, None, 3)`

Method `elrp` works fine, but `deeplift` raises an error. (Both traditional API and Explainer API.)
TypeError: 'NoneType' object cannot be interpreted as an integer.

In v0.1, it seems to work OK.

**Comment by linchundan88** [comment]
input_tensor = model.layers[0].input
    fModel = Model(inputs=input_tensor, outputs=model.layers[-1].output)
    target_tensor = fModel(input_tensor)
  
 In this case, input_tensor will be none.

**Comment by linchundan88** [comment]
Another problem, if I load a model from file, I must predict one time ,otherwise it will raise an exception:
"tensorflow.python.framework.errors_impl.InternalError: Blas SGEMM launch failed : m=21609, n=128, k=64

But if I use this model to predict one time, after that DeepExplain run well.

**Comment by marcoancona** [comment]
About the first issue, do you know the shape of the input? In this case, you can define the input shape in the model. DeepLIFT needs to run the model on a baseline first, so the dimensions need to be known (or you can pass the `baseline=` parameter explicitly)

**Comment by linchundan88** [comment]
> About the first issue, do you know the shape of the input? In this case, you can define the input shape in the model. DeepLIFT needs to run the model on a baseline first, so the dimensions need to be known (or you can pass the `baseline=` parameter explicitly)

I will try pass the `baseline=` parameter explicitly. I know deeplift(difference from reference, so we need a reference first). Thank you very much.

**Comment by linchundan88** [comment]
I do not know how to pass the baseline= parameter explicitly. Anyway, I can change the input shape in the model.
This issue can be closed.

**Comment by linchundan88** [comment]
baseline must be a numpy array with the size of the input. I found it.

such as :
baseline1 = np.zeros((image_size, image_size, 3))
explainer = de.get_explainer('deeplift', target_tensor, input_tensor,
                                     baseline=baseline1)
