### ISSUE TITLE
If a model's input dimensions contain None

### ISSUE THREAD

**Issue by linchundan88** [marcoancona/DeepExplain#38]
I use deeplift.
If a model's input dimension is (None,None,None,3), when using deeplift, it will raise an exception.

After setting a baseline, it still raise an exception:
"RuntimeError: Baseline shape (299, 299, 3) does not match expected shape [None, None, 3]"
       for example:
        baseline = np.zeros((image_size, image_siz  e, 3))
        explainer = de.get_explainer('deeplift', target_tensor, input_tensor,
                                     baseline=baseline)

 I modified the method "_set_check_baseline" in file method.py from line 196,               

It runs well.

**Comment by linchundan88** [comment]
In my opinion, you should let None match any number value.

**Comment by marcoancona** [comment]
Makes sense to me. Does it work with your model using such a fix?

**Comment by linchundan88** [comment]
> Makes sense to me. Does it work with your model using such a fix?

 Yes, it works.

**Comment by marcoancona** [comment]
I will push the changes in the next days then.
