### ISSUE TITLE
Any plans to upgrade codebase to Tensorflow 2.x?

### ISSUE THREAD

**Issue by arundasan91** [marcoancona/DeepExplain#62]
Hi @marcoancona , I was wondering if there are any plans to upgrade the codebase to TF2.x. Wasn't able to find any roadmaps on the repo.

Thanks,
Arun

**Comment by marcoancona** [comment]
Hi!
DeepExplain uses some low-level API to implement DeepLIFT and LRP. It is not straight forward to port to TF2, although there is an open pull-request which adds compatibility with TF2 *when eager execution is disabled*. Would this help?

**Comment by arundasan91** [comment]
I shall check soon and reply back. Closing this for now.

**Comment by arundasan91** [comment]
Hi @marcoancona , I can confirm that `tensorflow.compat.v1.disable_eager_execution()` works on TF2. 

However I also added this to the code to make it work for my specific problem:
```
from tensorflow.compat.v1.keras.backend import get_session
from tensorflow.compat.v1.keras import backend as K
```
