### ISSUE TITLE
RecursionError when using Keras model - multiple_input_keras.ipynb

### ISSUE THREAD

**Issue by itsmemala** [marcoancona/DeepExplain#70]
Hi,

I have tried to run the multiple_input_keras.ipynb example on Google Colab but I get the following error:

RecursionError                            Traceback (most recent call last)
[<ipython-input-19-7e97bfdd098c>](https://localhost:8080/#) in <module>()
     33     target_tensor = fModel(input_tensors)
     34 
---> 35     attributions = de.explain('grad*input', target_tensor, input_tensors, [_x1, _x2])
     36     print ("Attributions:\n", attributions)

422 frames
[/usr/local/lib/python3.7/dist-packages/keras/engine/keras_tensor.py](https://localhost:8080/#) in __str__(self)
    308     return 'KerasTensor(type_spec=%s%s%s%s)' % (
    309         self.type_spec, inferred_value_string,
--> 310         name_string, symbolic_description)
    311 
    312   def __repr__(self):

RecursionError: maximum recursion depth exceeded

**Comment by Zhangyang823** [comment]
你好，来信已收到~~

**Comment by itsmemala** [comment]
This works now. I was using TF2 but after adding the below lines at the beginning of the code, it runs:
tf.compat.v1.disable_v2_behavior()
tf.compat.v1.disable_eager_execution()
